# Name your project! Project names should contain only lowercase characters
# and underscores. A good package name should reflect your organization's
# name or the intended use of these models
name: "nhl_mds_in_a_box_transform"
version: "1.0.0"

# This setting configures which "profile" dbt uses for this project.
profile: "nhl_mds_in_a_box_transform"

flags:
  send_anonymous_usage_stats: False

# These configurations specify where dbt should look for different types of files.
# The `model-paths` config, for example, states that models in this project can be
# found in the "models/" directory. You probably won't need to change these!
model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

clean-targets: # directories to be removed by `dbt clean`
  - "target"
  - "dbt_packages"

seeds:
  nhl_mds_in_a_box_transform:
    +quote_columns: false
    +database: staging
    +schema: reference

# Configuring models
# Full documentation: https://docs.getdbt.com/docs/configuring-models
models:
  nhl_mds_in_a_box_transform:
    staging:
      +database: staging
      +materialized: view
    intermediate:
      +database: intermediate
      +materialized: view
    marts:
      +database: marts
      +materialized: table
